spring:
  main:
    banner-mode: off
  profiles:
    active: dev
  redis:
    host: redis-dev
    port: 12021
    database: 0
    password: Redis@123!@#
  data:
    mongodb:
      host: localhost
      port: 27017
      database: advertise
  datasource:
    dynamic:
      primary: mysql
      datasource:
        mysql:
          url: jdbc:mysql://localhost:3306/advertise?serverTimezone=Asia/Shanghai
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver
        doris:
          url: jdbc:mysql://server:9030/advertise?serverTimezone=Asia/Shanghai
          username: root
          password:
          driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 7000
mybatis:
  configuration:
    map-underscore-to-camel-case: true
xxl:
  job:
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin
      accessToken: default_token
      timeout: 3
    executor:
      appname: sample-service
      address:
      ip:
      port: 0
      logpath:
      logretentiondays: 30
      excludedpackage: